import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Main from "@/components/Main";
import About from "@/components/About";
import Skills from "@/components/Skills";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aaina | Website Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Main />
        <About />
        <Skills />
        <Projects />
        <Contact />
        {children}
      </body>
    </html>
  );
}
